### PR TITLE
Changes we made for demo

### PR DESCRIPTION
**Pull request by ermainz**

### CODE REVIEW

**Comment by ermainz** [comment]
@cindyyli @jaketodaro not really sure how to handle this, but here are the changes to Pannellum that Nick made and that we have been working off of. Do we just merge this as is?

**Comment by jaketodaro** [comment]
I thought we only needed to add one event trigger to panellum? We have to make this many changes?

**Comment by ermainz** [comment]
¯\_(ツ)_/¯ I'll look into these changes more closely and see what functional changes were made.

**Comment by ermainz** [comment]
Starting over....

**Pull request closed without merging**
